plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.nightfeed.widget'
    compileSdk 34

    defaultConfig {
        applicationId 'com.nightfeed.widget'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '1.3'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.work:work-runtime-ktx:2.9.1'
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
}
